version: "3"

services:
  db: 
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=chatdb
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

  server: 
    build: chat-server/
    environment:
      - PORT=6000
      - MONGO_URI=mongodb://db:27017/chatdb
    ports:
      - 6000:6000
    volumes:
      - ./chat-server/:/opt/server
      - node_modules:/opt/server/node_modules
    depends_on:
      - db
  
  client:
    build: chat-client/
    ports:
      - 8080:8080
    depends_on:
      - server
      - db

volumes:
  dbdata:
  node_modules:
